### ISSUE TITLE
Mob heads broken when using pack with latest Voxelibre update

### ISSUE THREAD

**Issue by SxnnyB** [MysticTempest/REFI_Textures#9]
Mob heads have completely broken mesh, textures and icons with latest Voxelibre update.

Isuue may be related to the new capes system in VL as cape textures also over-ride elytra texture and mesh. 

When mob heads are worn or applied to an armor stand, the bugged mesh covers whole player mesh and adds a cape like feature even without elytra equipped. 

Mob heads are fine when not using texture pack.

Edit: carved pumpkin and stalker head appear to be unaffected.

**Comment by MysticTempest** [comment]
Looks like Voxelibre is what mineclone2 turned into. It's unsupported though.
As I stopped supporting MCL2 back when it hit version 0.80.
I'd recommend Mineclonia instead of voxelibre for the MC-like experience.

However, there is some backups of the head images (ending in '_old'); that you can try. You can run the bash script, or copy/rename them yourself.
**Bash script lines:**
https://github.com/MysticTempest/REFI_Textures/blob/master/alternate_textures/Alternate_Textures_Update_Script.sh#L340-L344

**Alt texture folder:**
https://github.com/MysticTempest/REFI_Textures/tree/master/alternate_textures/texture_alts
